version: '3.5'

services:
  postgres:
    image: postgres
    network_mode: bridge
    container_name: postgres_docker
    #volumes:
     # - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=articles
    restart: unless-stopped
  # APP*****************************************
  springbootapp:
    image: springboot-app:latest
    network_mode: bridge
    expose:
      - 8088
    ports:
      - 8088:8088
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  postgres:
  pgadmin: